default_install_hook_types: [ commit-msg, prepare-commit-msg, pre-commit ]
repos:
  - repo: local
    hooks:
      - id: check-commit-message
        name: Check commit message format
        language: python
        entry: python scripts/check_commit_message.py
        stages: [ commit-msg ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
