name: findme
services:
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  serverless:
    build: ./backend
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - NODE_OPTIONS=--max_old_space_size=4096
      - AWS_ENDPOINT_URL=http://localstack-main:4566/
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - localstack

  frontend:
    build:
      context: ./frontend
    environment:
      - API_URL=http://findme.execute-api.localstack-main.localstack.cloud:4566
    depends_on:
      - serverless
    volumes:
      - "./frontend:/app"
    ports:
      - "8100:8100"
