version: '3.8'
services:
  localstack:
    container_name: "findme-localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
       - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  serverless:
    build: ./backend
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - NODE_OPTIONS=--max_old_space_size=4096
    volumes:
      - ".:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - localstack
    command: >
      sh -c "
        while ! nc -z findme-localstack 4566; do
          echo 'Waiting for LocalStack to be ready...';
          sleep 1;
        done;
        echo 'LocalStack is up. Deploying Serverless app...';
        serverless deploy --stage dev --verbose;
      "
